---
# This playbook deploys DC/OS

- name: apply common configuration to all nodes
  hosts: all
  serial: 10
  become: true

  roles:
    - common

- name: generate the DC/OS configuration
  hosts: workstations
  serial: 10
  become: true

  roles:
    - workstation

- name: deploy DC/OS masters
  hosts: masters
  serial: 10
  become: true

  roles:
    - master

- name: deploy DC/OS agents
  hosts: agents
  serial: 10
  become: true

  roles:
    - agent

- name: deploy DC/OS public agents
  hosts: agents_public
  serial: 10
  become: true

  roles:
    - agent_public
